name: omnimodel
description: Model complex data and access it in an easy and safe way. OmniModel wraps data structures and allows the developer to handle missing entries and fields
repository: https://github.com/tratteo/omnimodel
version: 1.1.0

environment:
    sdk: ">=2.18.5 <4.0.0"

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
dependencies:
    tint: ^2.0.1
