name: omnimodel
description: Model complex data and access it in an easy and safe way. OmniModel wraps data structures and allows the developer to handle missing entries and fields
repository: https://github.com/tratteo/omnimodel
version: 1.1.10
environment:
    sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
    lints: ^5.0.0
    test: ^1.25.8
dependencies:
    tint: ^2.0.1
