name: omnimodel
description: Model complex data and access it in an easy and safe way
repository: https://github.com/tratteo/omnimodel
version: 1.0.4

environment:
    sdk: ">=2.18.5 <3.0.0"

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
